-- Programmers(SQL): 업그레이드 된 ITEM 구하기 
-- 아이템의 희귀도가 'Rare' 아이템만 추출, 
-- 그 중 다음 업그레이드 아이템의 ID 출력 
-- ORDER BY ITEM_ID ASC; 

SELECT II.ITEM_ID, II.ITEM_NAME, II.RARITY
FROM ITEM_INFO AS II
    INNER JOIN ITEM_TREE AS IT
        ON II.ITEM_ID = IT.ITEM_ID
WHERE IT.PARENT_ITEM_ID IN (SELECT ITEM_ID FROM ITEM_INFO WHERE RARITY = 'RARE')
ORDER BY IT.ITEM_ID DESC;